version: '3.8'

services:
  app:
    build: ./
    container_name: nestjs_app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MONGO_URI=${MONGO_URI}
    ports:
      - '3000:3000'
    networks:
      - nestjs_network
networks:
  nestjs_network:
    driver: bridge
